### ISSUE TITLE
move cdg and cdg_renderer to their own repo?

### ISSUE THREAD

**Issue by gdesmott** [thequux/qaraoke#5]
Hi @thequux,

If you are no longer interested in maintaining the cdg crates I was wondering if you'd consider moving them to their own repos. I'd be happy to take over maintenance but I'd rather do it as a separated project to not accidentally break qaraoke as I don't use it. :)

**Comment by gdesmott** [comment]
@thequux : any chance to move forward with this? I have patches I'd like to integrate. thanks!

**Comment by thequux** [comment]
Hi, sorry I took so long :-(
I just created the cdg-rs organization, which you should be a member of; that has repositories for both cdg and cdg_renderer. Will that work?

**Comment by gdesmott** [comment]
I think so. Last remaining step is updating the repo address on crates.io and grant me the credentials there as well so I can push releases.

thanks!

**Comment by thequux** [comment]
I've invited you to be an owner on crates.io for both crates; the repo address can only be changed when we push the next release (and it doesn't make sense, IMHO, to publish a release *just* to update the repo)

**Comment by gdesmott** [comment]
Oh indeed, I missed the invite; accepted it now.
I'll make a renderer release with my reset patch then and will update the repo as well.

Thanks a lot!

**Comment by gdesmott** [comment]
Looks like I don't have the rights to push to the git repos. I think you should give the admin rights to the member of the `cdg-rs` organization.

**Comment by gdesmott** [comment]
I think we're good now. I managed to push to the repo and [publish a release on crates.io](https://crates.io/crates/cdg_renderer/0.4.0).

From now, should I push changes directly to the repo or do you prefer to keep reviewing them first?

Thanks again for your work on these crates and your trust.

**Comment by thequux** [comment]
Go ahead and push directly to the repo; I hope to pick up development of
qaraoke again this year, so I should notice if anything goes wrong.
